import { Node, Edge } from 'reactflow';

/**
 * 将 React Flow 的节点和边转换为 Mermaid 语法
 * @param nodes React Flow 节点数组
 * @param edges React Flow 边数组
 * @param direction 布局方向 'TB' (Top to Bottom) 或 'LR' (Left to Right)
 * @returns Mermaid 格式的字符串
 */
export function convertToMermaid(nodes: Node[], edges: Edge[], direction: 'TB' | 'LR' = 'TB'): string {
  let mermaid = `graph ${direction}\n`;

  // 1. 定义节点和样式
  nodes.forEach((node) => {
    const label = node.data.label.replace(/"/g, "'"); // 防止引号冲突
    const category = node.data.category;
    
    // 根据类别选择不同的形状
    // Goal: 双边框, Prerequisite: 圆角, Action: 矩形, Known: 虚线
    let nodeDef = '';
    if (category === 'goal') {
      nodeDef = `  ${node.id}(["${label}"])`;
    } else if (category === 'prerequisite') {
      nodeDef = `  ${node.id}(["${label}"])`;
    } else if (category === 'known') {
      nodeDef = `  ${node.id}["${label}"]`;
    } else {
      nodeDef = `  ${node.id}["${label}"]`;
    }
    
    mermaid += `${nodeDef}\n`;
  });

  // 2. 定义边
  edges.forEach((edge) => {
    mermaid += `  ${edge.source} --> ${edge.target}\n`;
  });

  // 3. 定义样式类 (Mermaid classDef)
  mermaid += '\n  %% 样式定义\n';
  mermaid += '  classDef goal fill:#f96,stroke:#333,stroke-width:4px;\n';
  mermaid += '  classDef prerequisite fill:#fff,stroke:#f66,stroke-width:2px,stroke-dasharray: 5 5;\n';
  mermaid += '  classDef known opacity:0.5,stroke-dasharray: 5 5;\n';
  mermaid += '  classDef default fill:#fff,stroke:#333,stroke-width:1px;\n';

  // 4. 应用样式类
  nodes.forEach((node) => {
    const category = node.data.category;
    if (category === 'goal') {
      mermaid += `  class ${node.id} goal;\n`;
    } else if (category === 'prerequisite') {
      mermaid += `  class ${node.id} prerequisite;\n`;
    } else if (category === 'known') {
      mermaid += `  class ${node.id} known;\n`;
    }
  });

  // 5. 添加品牌标识（Mermaid 注释格式）
  mermaid += '\n  %% Generated by LinkLog - https://linklog.ai-builders.space\n';

  return mermaid;
}
